### ISSUE TITLE
Font change ?

### ISSUE THREAD

**Issue by amarc** [RainerChiang/simpleness#4]
Hello, thanks for lovely theme..

Wondering where can I change logo font and overall font of blog to something else.. ? 

ty.

**Comment by brunoamaral** [comment]
You can do that by editing the CSS files found here:

https://github.com/RainerChiang/simpleness/tree/main/static/css

fonts.css loads them from google fonts or your favorite provider, and simpleness.css offers variables that you can change to use your own fonts without messing too much with the code.

For extra safety, you can place your changed files in /static/css/ so that Hugo will use them. This way, you can keep updating the theme without breaking things (too much) 🙂

**Comment by RainerChiang** [comment]
@brunoamaral, Thank you very much for your patience in answering these questions.
